version: "3"

services:
  node:
    image: node-ttyd:latest
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
      - "35729:35729"

volumes:
  node_modules:
